name: CD

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t your-image-name -f docker/Dockerfile .
      
    - name: Log in to Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker tag your-image-name your-registry/your-image-name:${{ github.sha }}
        docker push your-registry/your-image-name:${{ github.sha }}